import { Reparacion } from "../pages/reparaciones/reparacion.models";

export class Maniobra {
    constructor(
        public cargaDescarga?: string,
        public folio?: string,
        public viaje?: string,
        public agencia?: string,
        public cliente?: string,
        public transportista?: string,
        public camion?: string,
        public operador?: string,
        public contenedor?: string,
        public tipo?: string,
        public grado?: string,
        public peso?: string,
        public destinatario?: string,
        public estatus?: string,
        public fLlegada?: string,
        public hLlegada?: string,
        public hEntrada?: string,
        public facturarA?: string,
        public correoFac?: string,
        public correoOp?: string,
        public solicitud?: string,
        public hSalida?: string,
        public descargaAutorizada?: boolean,
        public hDescarga?: string,
        public lavado?: string,
        public lavadoObservacion?: string,
        public reparaciones?: Reparacion[],
        public reparacionesObservacion?: string,
        public fTerminacionLavado?: string,
        public hTerminacionLavado?: string,
        public fTerminacionReparacion?: string,
        public hTerminacionReparacion?: string,
        public maniobraAsociada?: Maniobra,
        public facturaManiobra?: string,
        public fAsignacionPapeleta?: string,
        public fExpiracionPapeleta?: string,
        public usuarioAlta?: string,
        public fAlta?: Date,
        public usuarioMod?: string,
        public fMod?: Date,
        public _id?: string
    ) {}
}
